baseURL = "https://blog.jirkachadima.cz/"
languageCode = "en-us"
title = "Blog was not built in a day"
theme = "hugo-cactus-theme"
googleAnalytics = "G-M3VPYYBKRV"

[params]
  name = "Jirka Chadima"
  description = "Blog was not built in a day"
  bio = "Blog was not built in a day"
  aboutAuthor = "Blog was not built in a day"
  enableRSS = true
  iconFont = "font-awesome"
  copyright = "Est. 2020. All content is licensed under CC-BY-SA 4.0"

[social]
    twitter  = "https://twitter.com/jirkachadima"
    github   = "https://www.github.com/jirkachadima"
